apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rohith-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rohith-marigowda/argoCd.git
    targetRevision: HEAD
    path: ./
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  automated:
	  selfHeal: true
	  prune: true
